name: Report Issue
description: Report an issue with an aGG / XFGN Service
title: "[Issue]: "
labels: ["bug"]
body:
- type: input
  id: affected
  attributes:
    label: App Affected
    description: "What app/s are affected by this?"
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description of issue
    description: "Description of the issue you're seeing"
    render: bash
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      4.
      5.
    render: bash
  validations:
    required: false
- type: textarea
  id: expected
  attributes:
    label: Expected Behaviour
    description: "What are you expecting to happen?"
    render: bash
  validations:
    required: true
- type: dropdown
  id: impact
  attributes:
    label: What priority is this?
    options:
      - Low
      - Medium
      - High
      - Urgent
  validations:
    required: true
- type: checkboxes
  id: investigation
  attributes:
    label: Investigation Done
    description: Status of issue
    options:
      - label: Root cause found
      - label: Fix implemented
      - label: Fix confirmed
