name: Documentation Change
description: Make a correction to our documentation
title: "[doc]: "
labels: ["documentation"]
body:
- type: input
  id: affected
  attributes:
    label: Link to Incorrect Doco
    description: "Provide a link to the page that needs correcting"
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Corrected information
    description: "Please provided the corrected information"
    render: bash
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
      4.
      5.
    render: bash
  validations:
    required: false
- type: textarea
  id: expected
  attributes:
    label: Expected Behaviour
    description: "What are you expecting to happen?"
    render: bash
  validations:
    required: true
- type: dropdown
  id: impact
  attributes:
    label: What priority is this?
    options:
      - Low
      - Medium
      - High
      - Urgent
  validations:
    required: true
- type: checkboxes
  id: investigation
  attributes:
    label: Investigation Done
    description: Status of issue
    options:
      - label: Root cause found
      - label: Fix implemented
      - label: Fix confirmed
