name: Documentation Change
description: Make a correction to our documentation
title: "[doc]: "
labels: ["documentation"]
body:
- type: input
  id: affected
  attributes:
    label: Link to Incorrect Doco
    description: "Provide a link to the page that needs correcting"
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Corrected information
    description: "Please provided the corrected information"
    render: bash
  validations:
    required: true
