---
version: "2.1"
services:
  app:
    image: ghcr.io/bakito/adguardhome-sync:v0.5.2@sha256:f0b1e12c90a909ac3de5d8cc9326f206833937d23ac0e64bc20d93abd2144d1d
    command: run
    environment:
      LOG_LEVEL: 'debug'
      ORIGIN_URL: http://$HOST_URL
      ORIGIN_USERNAME: $HOST_UN
      ORIGIN_PASSWORD: $HOST_PW
      REPLICA_URL: http://$SLAVE_URL
      REPLICA_USERNAME: $SLAVE_UN
      REPLICA_PASSWORD: $SLAVE_PW
      # REPLICA1_AUTOSETUP: true # if true, AdGuardHome is automatically initialized.
      # REPLICA1_INTERFACENAME: 'ens18' # use custom dhcp interface name
      # REPLICA1_DHCPSERVERENABLED: true/false (optional) enables/disables the dhcp server on the replica
      CRON: '*/1 * * * *' # run every 1 minutes
      RUNONSTART: true

      # Configure the sync API server, disabled if api port is 0
      API_PORT: $PORT

      # Configure sync features; by default all features are enabled.
      # FEATURES_GENERALSETTINGS: true
      # FEATURES_QUERYLOGCONFIG: true
      # FEATURES_STATSCONFIG: true
      # FEATURES_CLIENTSETTINGS: true
      # FEATURES_SERVICES: true
      # FEATURES_FILTERS: true
      # FEATURES_DHCP_SERVERCONFIG: true
      # FEATURES_DHCP_STATICLEASES: true
      # FEATURES_DNS_SERVERCONFIG: true
      # FEATURES_DNS_ACCESSLISTS: true
      # FEATURES_DNS_REWRITES: true
    ports:
      - $PORT:$PORT
    restart: unless-stopped
