version: "2.3"
services:
  app:
    image: cloudflare/cloudflared:2024.4.1
    restart: unless-stopped
    network_mode: host
    environment:
      - TUNNEL_METRICS=127.0.0.1:${PORT:-5566}
    command: tunnel run -token $CLOUDFLARE_UUID
    ports:
      - ${PORT:-5566}:${PORT:-5566} 
