version: '3'
services:
  app:
    image: cloudflare/cloudflared:2024.5.0
    restart: unless-stopped
    network_mode: host
    environment:
      - TUNNEL_METRICS=0.0.0.0:5566
    command: tunnel run -token $CLOUDFLARE_UUID
