version: '3'
services:
  app:
    image: cloudflare/cloudflared:2025.5.0
    restart: unless-stopped
    network_mode: host
    environment:
      - TUNNEL_METRICS=0.0.0.0:5566
    command: tunnel run -token $CLOUDFLARE_UUID
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  healthcheck:
    image: quay.io/curl/curl:8.10.1
    init: true
    command: sleep infinity
    depends_on:
      - app
    healthcheck:
      test: ['CMD-SHELL', 'curl -fsS http://app:5566/ready']
      interval: 1s
      timeout: 2s
      retries: 60
