version: '3'
services:
  app:
    image: cloudflare/cloudflared:2025.6.0@sha256:783e0e52ddad1e91f0dba5f305fc7a8dc94afab8b4c8c309bcd17c5a45654dfb
    restart: unless-stopped
    network_mode: host
    environment:
      - TUNNEL_TOKEN=$CLOUDFLARE_UUID
      - TUNNEL_METRICS=0.0.0.0:5566
    command: tunnel run
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]       # Check if cloudflared version command works
      interval: 60s                                   # Time between health check attempts
      timeout: 55s                                    # Time to wait for a response
      retries: 3                                      # Number of retries before marking as unhealthy
      start_period: 30s                               # Delay before health checks begin
    labels:
      - "autoheal=true"
