version: '3'
services:
  app:
    image: cloudflare/cloudflared:2024.4.1
    restart: unless-stopped
    network_mode: host
    environment:
      - TUNNEL_METRICS=0.0.0.0:5566
    command: tunnel run -token $CLOUDFLARE_UUID
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k 127.0.0.1:5566/ready
      interval: 5s
      retries: 6
      timeout: 3s
      start_period: 5s
