version: "3"
services:
  play:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY=$CLOUDFLARE_APIKEY     #Required
      - ZONE=$DOMAIN                   #Required
      - SUBDOMAIN=$SUBDOMAIN           #Not required
      - PROXIED=$PROXIED               #Required: true/false

