---
version: "2.1"
services:
  app:
    image: ghcr.io/linuxserver/duplicati:v2.0.7.1-2.0.7.1_beta_2023-05-25-ls188
    environment:
      - PUID=0 #Root user
      - PGID=0 #Root user
      - TZ=$TZ
      - CLI_ARGS= #optional
    hostname: ${ALIAS:-duplicati}
    volumes:
      - config:/config
      - /:/macaroni
    ports:
      - ${PORT:-8200}:8200
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:8200
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  config:
