---
version: "2.1"
services:
  app:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.13
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=$TZ
    ports:
      - $PORT:8191
    restart: unless-stopped
    mem_limit: 2G
