---
version: "2.1"
services:
  app:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.25
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=$TZ
    ports:
      - ${PORT:-8191}:8191
    restart: unless-stopped
    mem_limit: 2G
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:8191
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
