version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:8.0.3@sha256:ffd91433531942ee9eb303a3c17699e894148294bef8cdec9e58b85fb16e84d1
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
