version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:7.3.14@sha256:bfa12dadc049bf5b24e3db1e1a6a434817db0e36f0f60460dc6b2c29a868ff28
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}

volumes:
  config:
