version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:7.4.2@sha256:9cdfcf13749b68911d333eb3a09096517e5efa0236017ccfe30bc42de01d8715
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}

volumes:
  config:
