version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:7.7.5@sha256:e73512701a6f56dede45b46573c9e31b81d447c9fdc049dbb164af4cb5f22b20
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
