version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:7.2.1@sha256:247223d97ca95ca47f65495bf2cbafdb3d151c9bca657df7c29375abe944dcc9
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}

volumes:
  config:
