version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:7.5.7@sha256:8e6d9dbb07e20acd98d42d4f63e51467e902e4f96e7a1dc6cfd53506a7fd9d5c
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
