version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:8.1.8@sha256:c31d6da9a27ab589a0846b7ad691dd920a0f8fea746ed9d232d56c6ad7d85b91
    hostname: ${ALIAS:-huntarr}
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
