version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:8.1.4@sha256:48ca6bfca24f8c81e5575e5233751e04cd0a36292fc9220966e4a2522302b43e
    hostname: ${ALIAS:-huntarr}
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
