version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:7.4.4@sha256:13d205313f30eb50fa483690c503340a4b532cecb65997de6f5956e7dd4ac0c5
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
