version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:6.5.18@sha256:987022291e25fb95010e9924a5e80a3bfebd6a10a247dc4eefea4b16751a82de
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}

volumes:
  config:
