version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:7.8.0@sha256:ff22cfc9591fc9201437d0f1aeff459e38d7ee63a417163d4da9a7ed09f3d0a5
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
