version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:6.0.4@sha256:89fbe81534162e65d7aec6b2b6e7c4d58d06b79fa9652be830fb121699c0bdfb
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}

volumes:
  config:
