version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:8.1.10@sha256:d2fb428820f72acce66b9275eb4ee6092a0527d0fe4e50acd0b6548ede17ac90
    networks:
      - cloudflare-net
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dockflare.0.service=http://${HOSTNAME}:${PORT:-9705}
      - dockflare.0.access.policy=${CFPOLICY:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN}
      - dockflare.0.path=${CFURLPATH:-}
volumes:
  config:
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true
