version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:8.1.15@sha256:a705e690e20bfd6f52081c126a3dc8d6e987374c9feda8c146a56ddac42dca47
    networks:
      - cloudflare-net
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dockflare.0.service=http://${HOSTNAME:-localhost}:${PORT:-9705}
      - dockflare.0.access.policy=${CFPOLICY:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN}
      - dockflare.0.path=${CFURLPATH:-}
volumes:
  config:
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true
