version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:8.0.4@sha256:0639df45a9f9eb81039a35c48f28bdd261d204abd595c1e00584011599651256
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
