version: '3.8'

services:
  app:
    image: ghcr.io/plexguide/huntarr:7.5.11@sha256:c5dd24455564806e1a447af2c6a42d9267b1c3a0ae6877177967f10e6c98a6fd
    restart: always
    ports:
      - ${PORT:-9705}:9705
    volumes:
      - config:/config
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    healthcheck:
      test: netstat -ltn | grep -c ":9705"
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"

volumes:
  config:
