version: "2.3"
services:
  app:
    image: ghcr.io/linuxserver/kasm:1.17.0@sha256:eafbaeae3060c4bd263fde845883e31a818f124f3f0103b86de3cf633e151d2b
    privileged: true
    networks:
      - cloudflare-net
    environment:
      - PUID=1000
      - PGID=1000
      - KASM_PORT=444
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=all
      - TZ=${TZ:-Australia/Melbourne}
    runtime: nvidia
    volumes:
      - opt:/opt
      - profiles:/profiles #persistent storage
      - /dev/input:/dev/input #input support
      - /run/udev/data:/run/udev/data #input support
      - thumbnails:/kasm_release/www/img/thumbnails
      - /opt/kasm/current/log/agent_json.log:/opt/kasm/current/log/agent_json.log ##CrowdSec logs
    ports:
      - ${PORT_SETUP:-3000}:3000 #Setup WebGUI
      - ${PORT:-444}:444
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k https://localhost:444/api/__healthcheck
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 15s
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dockflare.0.service=https://${HOSTNAME:-localhost}:${PORT:-444}
      - dockflare.0.access.policy=${CFPOLICY:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN}
      - dockflare.0.path=${CFURLPATH:-}
      - dockflare.0.no_tls_verify=true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  opt:
  profiles:
  thumbnails:
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true
