version: "2.1"
services:
  app:
    image: ghcr.io/linuxserver/kasm:version-1.14.0.1@sha256:0fc0bdab8a99e1ae370c90af1b56ff1812f113ac06a7d3f96094c7c6be4d6e35
    privileged: true
    environment:
      #- PUID=1000
      #- PGID=1000
      - KASM_PORT=444
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - TZ=$TZ
    runtime: nvidia
    volumes:
      - opt:/opt
      - profiles:/profiles #persistent storage
      - /dev/input:/dev/input #input support
      - /run/udev/data:/run/udev/data #input support
      - thumbnails:/kasm_release/www/img/thumbnails
      - /opt/kasm/current/log/agent_json.log:/opt/kasm/current/log/agent_json.log ##CrowdSec logs
    ports:
      - $PORT_SETUP:3000 #Setup WebGUI
      - $PORT:444
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:444
      retry: 3
      start-period: 20s
      timeout: 10s

volumes:
  opt:
  profiles:
  thumbnails:
