version: "2.3"
services:
  app:
    image: ghcr.io/linuxserver/kasm:1.15.0-ls24
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - KASM_PORT=444
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=all
      - TZ=$TZ
    #runtime: nvidia
    volumes:
      - opt:/opt
      - profiles:/profiles #persistent storage
      - /dev/input:/dev/input #input support
      - /run/udev/data:/run/udev/data #input support
      - thumbnails:/kasm_release/www/img/thumbnails
      - /opt/kasm/current/log/agent_json.log:/opt/kasm/current/log/agent_json.log ##CrowdSec logs
    ports:
      - ${PORT_SETUP:-3000}:3000 #Setup WebGUI
      - ${PORT:-444}:444
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k https://localhost:444/api/__healthcheck
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 15s
    #labels:
    #  - "autoheal=true"

volumes:
  opt:
  profiles:
  thumbnails:
