version: "2.3"
services:
  app:
    image: ghcr.io/linuxserver/kasm:1.17.0@sha256:cc7d53bc0b6a3117cf7eb5ce355c2f6eee76f7632f77bc8982de69f7ab8f51d0
    privileged: true
    hostname: ${ALIAS:-kasm}
    environment:
      - PUID=1000
      - PGID=1000
      - KASM_PORT=444
      #- NVIDIA_VISIBLE_DEVICES=all
      #- NVIDIA_DRIVER_CAPABILITIES=all
      - TZ=$TZ
    runtime: nvidia
    volumes:
      - opt:/opt
      - profiles:/profiles #persistent storage
      - /dev/input:/dev/input #input support
      - /run/udev/data:/run/udev/data #input support
      - thumbnails:/kasm_release/www/img/thumbnails
      - /opt/kasm/current/log/agent_json.log:/opt/kasm/current/log/agent_json.log ##CrowdSec logs
    ports:
      - ${PORT_SETUP:-3000}:3000 #Setup WebGUI
      - ${PORT:-444}:444
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k https://localhost:444/api/__healthcheck
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 15s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  opt:
  profiles:
  thumbnails:
