version: "3.8"

services:
  api:
    image: ghcr.io/danny-avila/librechat:v0.7.2
    ports:
      - ${PORT:-3080}:3080
    restart: unless-stopped
    env_file:
      - ../stack.env
    volumes:
      - librechat_images:/app/client/public/images
    networks:
      librechat:
        aliases:
          - api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  meilisearch:
    image: getmeili/meilisearch:v1.5.1
    restart: unless-stopped
    env_file:
      - ../stack.env
    volumes:
      - meili_data:/meili_data
    networks:
      librechat:
        aliases:
          - meilisearch
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
          
  mongodb:
    image: mongo
    restart: unless-stopped
    #user: "${UID}:${GID}"
    env_file:
      - ../stack.env
    volumes:
      - mongo_data:/data/db
    command: mongod --noauth
    networks:
      librechat:
        aliases:
          - mongodb
    healthcheck:
      test: ["CMD-SHELL", "pidof mongod || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  librechat_images:
    driver: local
  meili_data:
    driver: local
  mongo_data:
    driver: local

networks:
  librechat:
    driver: bridge
