version: "3.8"

services:
  api:
    image: ghcr.io/danny-avila/librechat:v0.7.1
    ports:
      - ${PORT:-3080}:3080
    restart: unless-stopped
    env_file:
      - ../stack.env
    volumes:
      - librechat_images:/app/client/public/images
    networks:
      librechat:
        aliases:
          - api
    #healthcheck:
      #test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:3080/login
      #interval: 30s
      #retries: 3
      #start_period: 30s
      #timeout: 20s
    #labels:
      #- "autoheal=true"

  meilisearch:
    image: getmeili/meilisearch:v1.5.1
    restart: unless-stopped
    env_file:
      - ../stack.env
    volumes:
      - meili_data:/meili_data
    networks:
      librechat:
        aliases:
          - meilisearch
    healthcheck:
      test: ["CMD-SHELL", "pidof mongod || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "autoheal=true"
          
  mongodb:
    image: mongo
    restart: unless-stopped
    #user: "${UID}:${GID}"
    env_file:
      - ../stack.env
    volumes:
      - mongo_data:/data/db
    command: mongod --noauth
    networks:
      librechat:
        aliases:
          - mongodb
    #healthcheck:
      #test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      #interval: 30s
      #timeout: 10s
      #start_period: 30s
      #retries: 5
    #labels:
      #- "autoheal=true"

volumes:
  librechat_images:
    driver: local
  meili_data:
    driver: local
  mongo_data:
    driver: local

networks:
  librechat:
    driver: bridge
