version: '3'
services:
  app:
    image: ghcr.io/jorenn92/maintainerr:2.17.0@sha256:d0700764e30cfb6c10b3e13c555427f931f2193c57effa3938458f146da504df
    volumes:
      #- $MEDIA:$MEDIA
      - data:/opt/data
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      - BASE_PATH=/${BASEPATH:-}
      - debug=true
    ports:
      - ${PORT:-6246}:6246 
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://app:6246/${BASEPATH:-} || exit 1
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"
volumes:
  data:
