version: '3'
services:
  app:
    image: ghcr.io/jorenn92/maintainerr:2.19.0@sha256:bee84707edaf589cda3d18b6813cbfe3a137b52786210c3a28190e10910c1240
    hostname: ${ALIAS:-maintainerr}
    volumes:
      #- $MEDIA:$MEDIA
      - data:/opt/data
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      - BASE_PATH=${CFURLPATH:-}
      - debug=true
    ports:
      - ${PORT:-6246}:6246 
    restart: unless-stopped
    networks:
      - cloudflare-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://app:6246/${BASEPATH:-} || exit 1
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dockflare.0.service=http://${HOSTNAME:-localhost}:${PORT:-6246}
      - dockflare.0.access.policy=${CFPOLICY:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN}
      - dockflare.0.path=${CFURLPATH:-}      
volumes:
  data:
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true
