version: '3'
services:
  app:
    image: ghcr.io/jorenn92/maintainerr:2.18.1@sha256:da4b3b5b5e0a4aae6b4e294abdad2510a3be9bd138af8f4ca5a6e7cd6d94b1a2
    hostname: ${ALIAS:-maintainerr}
    volumes:
      #- $MEDIA:$MEDIA
      - data:/opt/data
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      - BASE_PATH=${CFURLPATH:-}
      - debug=true
    ports:
      - ${PORT:-6246}:6246 
    restart: unless-stopped
    networks:
      - cloudflare-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://app:6246/${BASEPATH:-} || exit 1
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dockflare.0.service=http://${HOSTNAME}:${PORT:-6246}
      - dockflare.0.access.policy=${CFPOLICY:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN}
      - dockflare.0.path=${CFURLPATH:-}      
volumes:
  data:
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true
