version: '3'
services:
  app:
    image: ghcr.io/jorenn92/maintainerr:2.10.0@sha256:e4d6c5c1017a2e6969d87c10d3c80f5d221096dc06863c5004774ea5c7621606
    volumes:
      #- $MEDIA:$MEDIA
      - data:/opt/data
    environment:
      - TZ=${TZ:-Australia/Melbourne}
      - BASE_PATH=/${BASEPATH:-}
      - debug=true
    ports:
      - ${PORT:-6246}:6246 
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    #healthcheck:
    #  test: wget --no-verbose --tries=1 --spider http://localhost:6246 || exit 1
    #  interval: 30s
    #  retries: 3
    #  start_period: 30s
    #  timeout: 20s
    #labels:
    #  - "autoheal=true"
volumes:
  data:
