version: "3"
services:
  app:
    image: ghcr.io/nickshanks347/monitarr:latest
    ports:
      - ${PORT:-3000}:3000
    environment:
      - SONARR_URL=$SONARRURL
      - SONARR_API_KEY=$SONARRAPI
      - RADARR_URL=$RADARRURL
      - RADARR_API_KEY=$RADARRAPI
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://app:3000 || exit 1
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
