version: "3"
services:
  app:
    image: ghcr.io/nickshanks347/monitarr:latest
    ports:
      - ${PORT:-3000}:3000
    environment:
      - SONARR_URL=$SONARRURL
      - SONARR_API_KEY=$SONARRAPI
      - RADARR_URL=$RADARRURL
      - RADARR_API_KEY=$RADARRAPI
    restart: unless-stopped
    networks:
       - cloudflare-net
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://app:3000 || exit 1
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dockflare.0.service=http://${HOSTNAME}:${PORT:-3000}
      - dockflare.0.access.policy=${CFPOLICY:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN}
      - dockflare.0.path=${CFURLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
networks:
    cloudflare-net:
        name: cloudflare-net
        external: true
