version: '3.7'
services:
  app:
    image: ghcr.io/danvergara/morphos-server:0.6.0
    hostname: ${ALIAS:-morphos}
    ports:
      - ${PORT:-8080}:8080
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
