version: '3'
services:
  app:
    image: lukechannings/moviematch:1.10.0
    restart: unless-stopped
    environment:
      - PLEX_URL=$PLEX_URL
      - PLEX_TOKEN=$PLEX_TOKEN
      - ROOT_PATH=$ROOTPATH
      - ROOTPATH=$ROOTPATH
    ports:
      - ${PORT:-8000}:8000   
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
