version: '3'
services:
  app:
    image: lukechannings/moviematch:1.10.0
    networks:
      - cloudflare-net
    restart: unless-stopped
    environment:
      - PLEX_URL=$PLEX_URL
      - PLEX_TOKEN=$PLEX_TOKEN
      - ROOT_PATH=$ROOTPATH
      - ROOTPATH=$ROOTPATH
    ports:
      - ${PORT:-8000}:8000   
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    labels:
      - cloudflare.tunnel.enable=true
      - cloudflare.tunnel.hostname=${SUBDOMAIN}${DOMAIN}
      - cloudflare.tunnel.service=HTTP://${HOSTNAME}:${PORT:-8000}
      - cloudflare.tunnel.access.policy=${CFPOLICY:-default_tld}
      - cloudflare.tunnel.zonename=${DOMAIN}
      - cloudflare.tunnel.path=${URLPATH:-}


networks:
  cloudflare-net: 
    name: cloudflare-net 
    external: true
