---
version: "2.1"
services:
  app:
    image: ghcr.io/linuxserver/netbootxyz:version-0.6.7@sha256:0077dda7d1debdc353b79679b23634ce0a3eb5173e994f46a4d5da6884fc7c2e
    environment:
      - PUID=$PUID
      - PGID=$PUID
      - TZ=$TZ
      - MENU_VERSION=1.9.9 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - conf:/config
      - assets:/assets #Bootable Assets, eg live CDs
    ports:
      - $PORT_UI:3000 #WebUI
      - 69:69/udp #TFTP
      - $PORT_ASSETS:80 #Assets
    restart: unless-stopped

volumes:
  conf:
  assets:
