---
version: "2.1"
services:
  app:
    image: ghcr.io/linuxserver/netbootxyz:0.7.5@sha256:e322a329f384f1465198ca71e238a0afe84529d05d70a754d06412a457ca966b
    environment:
      - PUID=$PUID
      - PGID=$PUID
      - TZ=$TZ
      - MENU_VERSION=1.9.9 #optional
      - SUBFOLDER=/ #optional
    volumes:
      - conf:/config
      - assets:/assets #Bootable Assets, eg live CDs
    ports:
      - ${PORT_UI:-3000}:3000 #WebUI
      - 69:69/udp #TFTP
      - $PORT_ASSETS:80 #Assets
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:3000
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"      
volumes:
  conf:
  assets:
