version: '3'
services:
  app:
    image: ghcr.io/linuxserver/overseerr:1.34.0@sha256:1205b8873f3ea0a98890191d9e01da911d9509272462a46414ba0378a6d76288
    environment:
      - TZ=$TZ
    volumes:
      - app:/config
      #- www:/app/overseerr/public #rebrand overseerr https://github.com/sct/overseerr/issues/404#issuecomment-1659795118
    ports:
      - ${PORT:-5055}:5055
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:5055/api/v1/status
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true
      - cloudflare.tunnel.enable=true
      - cloudflare.tunnel.hostname=$SUBDOMIAN
      - cloudflare.tunnel.service=http://$HOSTNAME.agg.local:${PORT:-5000}
      - cloudflare.tunnel.access.policy=default_tld
      - cloudflare.tunnel.zonename=$DOMAIN
      - cloudflare.tunnel.path=${URLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"      
volumes:
  app:
  www:
