version: '3'
services:
  app:
    image: ghcr.io/linuxserver/overseerr:1.33.2@sha256:9a4ccc23bf0a5902425759f41e36a8765cf3c589743db24cc682a892cd25bd4b
    environment:
      - TZ=$TZ
    volumes:
      - app:/config
      #- www:/app/overseerr/public #rebrand overseerr https://github.com/sct/overseerr/issues/404#issuecomment-1659795118
    ports:
      - ${PORT:-5055}:5055
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:5055/api/v1/status
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"      
volumes:
  app:
  www:
