version: '3'
services:
  app:
    image: ghcr.io/linuxserver/overseerr:1.34.0@sha256:bad11167104f7b0ff0beb924c9568bb7ea991c225949a209d0b8b00a5434479d
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    volumes:
      - app:/config
      #- www:/app/overseerr/public #rebrand overseerr https://github.com/sct/overseerr/issues/404#issuecomment-1659795118
    ports:
      - ${WEBPORT:-5055}:5055
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:5055/api/v1/status
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true
      - cloudflare.tunnel.enable=true
      - cloudflare.tunnel.hostname=${SUBDOMAIN}.${DOMAIN}
      - cloudflare.tunnel.service=http://${HOSTNAME:-localhost}:${WEBPORT:-5055}
      - cloudflare.tunnel.access.policy=${CFPOLICY:-default_tld}
      - cloudflare.tunnel.zonename=${DOMAIN}
      - cloudflare.tunnel.path=${URLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"      
volumes:
  app:
  #www:

