---
version: "2.1"
services:
  app:
    image: ghcr.io/linuxserver/prowlarr:1.10.5.4116-ls41
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=$TZ
    volumes:
      - config:/config
      - media:/media
      - downloads:/downloads
    ports:
      - $PORT:9696
    restart: unless-stopped
    

volumes:
  config:
  media:
    driver_opts:
      type: nfs
      o: addr=$STORAGE,nfsvers=4
      device: :$MEDIA
  downloads:
    driver_opts:
      type: nfs 
      o: addr=$STORAGE,nfsvers=4
      device: :$DOWNLOAD
