---
version: "2.1"
services:
  app:
    image: ghcr.io/linuxserver/prowlarr:1.30.2@sha256:8883bf1c8afdd45dfb8146041d944656efac01208ef44b7bbdd2aa8b0fbc1782
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=$TZ
    volumes:
      - config:/config
      - media:/media
      - downloads:/downloads
    ports:
      - ${PORT:-9696}:9696
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:9696
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
volumes:
  config:
  media:
    driver_opts:
      type: nfs
      o: addr=$STORAGE,nfsvers=4
      device: :$MEDIA
  downloads:
    driver_opts:
      type: nfs 
      o: addr=$STORAGE,nfsvers=4
      device: :$DOWNLOAD
