version: '3.8'
services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.11.13@sha256:98a5b9622cd152c43f1795fbc443934a25828cb1b3f7b5979cd5efb58175e869
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - wings
    ports:
      - ${PORT_SFTP:-2022}:2022
      - ${PORT:-443}:443   #Web address port
      #- $PORT_UNKNOWN:8080
    tty: true
    environment:
      TZ: $TZ
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - config:/etc/pterodactyl/  #config file from Panel
      - /var/lib/pterodactyl/:/var/lib/pterodactyl/ #game server files
      - /var/log/pterodactyl/:/var/log/pterodactyl/ #Allows Crowdsec to read logs
      - /tmp/pterodactyl/:/tmp/pterodactyl/
      - /srv/daemon-data/:/srv/daemon-data/
      - logs:/app/storage/logs/ #Laravel log files
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/443 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - autoheal=true
      - cloudflare.tunnel.enable=true
      - cloudflare.tunnel.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - cloudflare.tunnel.service=http://${HOSTNAME:-localhost}:${PORT:-443}
      - cloudflare.tunnel.access.policy=${CFPOLICY:-default_tld}
      - cloudflare.tunnel.zonename=${CFDOMAIN}
      - cloudflare.tunnel.path=${CFURLPATH:-}

  db:
    image: mariadb:12.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${PORT_DB:-3306}:3306
    networks:
      - wings
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE="servers"
      - MYSQL_USER="pterodactyl"
      - MYSQL_PASSWORD=$SQL_PASS
      - MYSQL_ROOT_PASSWORD=$SQL_PASS_ROOT
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-proot", "--password=$MYSQL_PASS_ROOT"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
networks:
  wings:
    name: wings
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: wings
  pterodactyl_nw:
    driver: bridge


volumes:
  config: 
  lib:
  daemon:
  db:
  logs:


