---
version: "2.3"
services:
  app:
    image: ghcr.io/linuxserver/sonarr:4.0.11@sha256:4ba3bfa985b911129b449734bbf63749a03f6ef69b8ca37f2ecd74d46fabef1f
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=$TZ
    volumes:
      - config:/config
      - media:/tv #optional
      - downloads:/downloads
    ports:
      - ${PORT:-8989}:8989
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:8989/ping
      interval: 3m
      timeout: 30s
      retries: 3
      start_period: 30s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  config:
  media:
    driver_opts:
      type: nfs
      o: addr=$STORAGE,nfsvers=4
      device: :$MEDIA
  downloads:
    driver_opts:
      type: nfs 
      o: addr=$STORAGE,nfsvers=4
      device: :$DOWNLOAD
