---
version: "2.1"
services:
  app:
    image: ghcr.io/linuxserver/sonarr:develop-4.0.0.697-ls585
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=$TZ
    volumes:
      - config:/config
      - media:/tv #optional
      - downloads:/downloads
    ports:
      - $PORT:8989
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail $HOST:$PORT/ping
      interval: 3m
      timeout: 30s
      retries: 3
      start_period: 30s

volumes:
  config:
  media:
    driver_opts:
      type: nfs
      o: addr=$STORAGE,nfsvers=4
      device: :$MEDIA
  downloads:
    driver_opts:
      type: nfs 
      o: addr=$STORAGE,nfsvers=4
      device: :$DOWNLOAD
