version: '3.3'
services:
    app:
        image: henrywhitaker3/speedtest-tracker
        ports:
            - $PORT:80
        volumes:
            - /config:/config
        environment:
            - TZ=$TZ
            - OOKLA_EULA_GDPR=true
        logging:
            driver: "json-file"
            options:
                max-file: "10"
                max-size: "200k"
        restart: unless-stopped

volumes:
  config:
