version: "2.3"
services:
  server:
    image: ghcr.io/haveagitgat/tdarr:2.32.01
    restart: unless-stopped
    ports:
      - ${WEBUI:-8265}:8265 # webUI port
      - ${SERVER:-8266}:${SERVER:-8266} # server port
    environment:
      - TZ=Australia/Melbourne
      #- PUID=${PUID}
      #- PGID=${PGID}
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=${SERVER:-8266}
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=${SERVNAME:-Server}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - server:/app/server
      - configs:/app/configs
      - logs:/app/logs
      - media:/media
      - /cache:/temp
      - /etc/hostname:/etc/hostname:ro
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:8265
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    labels:
      - "autoheal=true"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
            
  nodeA:
    image: ghcr.io/haveagitgat/tdarr_node:2.32.01
    restart: unless-stopped
    network_mode: service:server
    environment:
      - TZ=Australia/Melbourne
      #- PUID=${PUID}
      #- PGID=${PGID}
      - UMASK_SET=002
      - nodeName=${NODENAME:-}NodeA
      - serverIP=0.0.0.0
      - serverPort=${SERVERPORT:-8266}
      - inContainer=true
      - ffmpegVersion=6
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - configs:/app/configs
      - logs:/app/logs
      - media:/media
      - /cache:/temp
      - /etc/hostname:/etc/hostname:ro
    devices:
      - /dev/dri:/dev/dri
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
volumes:
  server:
  configs:
  logs:
  media:
    driver_opts:
      type: "nfs"
      o: addr=$MEDIASERV,nfsvers=4
      device: $MEDIAPATH
