version: '3.3'

services:
  app:
    image: louislam/uptime-kuma:1.23.16-debian
    volumes:
      - app:/app/data
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
      - UPTIME_KUMA_CLOUDFLARED_TOKEN=$CFTOKEN
    ports:
      - ${PORT:-3001}:3001  # <Host Port>:<Container Port>
    restart: always
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://LOCALHOST:3001
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    networks:
      - cloudflare-net
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN0}${CFDOMAIN0}
      - dockflare.0.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dockflare.0.access.policy=${CFPOLICY0:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN0}
      - dockflare.0.path=${CFURLPATH0:-}

      - dockflare.1.hostname=${CFSUBDOMAIN1}${CFDOMAIN1}
      - dockflare.1.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dockflare.1.access.policy=${CFPOLICY1:-default_tld}
      - dockflare.1.zonename=${CFDOMAIN1}
      - dockflare.1.path=${CFURLPATH1:-}

      - dockflare.2.hostname=${CFSUBDOMAIN2}${CFDOMAIN2}
      - dockflare.2.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dockflare.2.access.policy=${CFPOLICY2:-default_tld}
      - dockflare.2.zonename=${CFDOMAIN2}
      - dockflare.2.path=${CFURLPATH2:-}

      - dockflare.3.hostname=${CFSUBDOMAIN3}${CFDOMAIN3}
      - dockflare.3.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dockflare.3.access.policy=${CFPOLICY3:-default_tld}
      - dockflare.3.zonename=${CFDOMAIN3}
      - dockflare.3.path=${CFURLPATH3:-}

      - dockflare.4.hostname=${CFSUBDOMAIN4}${CFDOMAIN4}
      - dockflare.4.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dockflare.4.access.policy=${CFPOLICY4:-default_tld}
      - dockflare.4.zonename=${CFDOMAIN4}
      - dockflare.4.path=${CFURLPATH4:-}

      - dockflare.5.hostname=${CFSUBDOMAIN5}${CFDOMAIN5}
      - dockflare.5.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dockflare.5.access.policy=${CFPOLICY5:-default_tld}
      - dockflare.5.zonename=${CFDOMAIN5}
      - dockflare.5.path=${CFURLPATH5:-}

      - dockflare.6.hostname=${CFSUBDOMAIN6}${CFDOMAIN6}
      - dockflare.6.service=http://${HOSTNAME:-localhost}:${PORT:-3001}
      - dockflare.6.access.policy=${CFPOLICY6:-default_tld}
      - dockflare.6.zonename=${CFDOMAIN6}
      - dockflare.6.path=${CFURLPATH6:-}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
volumes:
  app:
networks:
  cloudflare-net:
    name: cloudflare-net
    external: true
