version: '3.3'

services:
  app:
    image: louislam/uptime-kuma:1.23.10-debian
    volumes:
      - app:/app/data
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
      - UPTIME_KUMA_CLOUDFLARED_TOKEN=$CFTOKEN
    ports:
      - $PORT:3001  # <Host Port>:<Container Port>
    restart: always

volumes:
  app:
