version: '3.3'

services:
  app:
    image: louislam/uptime-kuma:1.23.6-debian
    volumes:
      - app:/app/data
    ports:
      - $PORT:3001  # <Host Port>:<Container Port>
    restart: always

volumes:
  app:
