version: '3.3'

services:
  app:
    image: louislam/uptime-kuma:1.23.16-debian
    hostname: ${ALIAS:-kuma}
    volumes:
      - app:/app/data
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true
      - UPTIME_KUMA_CLOUDFLARED_TOKEN=$CFTOKEN
    ports:
      - ${PORT:-3001}:3001  # <Host Port>:<Container Port>
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
volumes:
  app:
