---
version: "3.5"
services:
  app:
    image: ghcr.io/wizarrrr/wizarr:2025.5.1@sha256:60b140c23748de8b79d427486a406e2f6ba514ba53ba8783059852936e498a15
    ports:
      - ${PORT:-5690}:5690
    volumes:
      - db:/data/database
    restart: unless-stopped
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:5690
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  db:
