---
version: "3.5"
services:
  app:
    image: ghcr.io/wizarrrr/wizarr:2025.6.3@sha256:7f399ed4a39339aa413f5f551f043f9862a3ff03c7c27f6e3ef32abc4afcb1c4
    ports:
      - ${PORT:-5690}:5690
    volumes:
      - db:/data/database
      - steps:/data/wizard_steps
    restart: unless-stopped
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:5690
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
        - TZ=${TZ:-Australia/Melbourne}
        - DISABLE_BUILTIN_AUTH=${DISABLEAUTH:-false}
volumes:
  db:
  steps:
