---
version: "3.5"
services:
  app:
    image: ghcr.io/wizarrrr/wizarr:2025.6.5@sha256:45cbac99eb86f3f63b204022538e9b537f335ccdd2749ca360b8d58b41f7a896
    hostname: ${ALIAS:-wizarr}
    ports:
      - ${PORT:-5690}:5690
    volumes:
      - db:/data/database
      - steps:/data/wizard_steps
    restart: unless-stopped
    labels:
      - autoheal=true
      - dockflare.enable=${CFTUNNEL:-true}
      - dockflare.0.hostname=${CFSUBDOMAIN}${CFDOMAIN}
      - dockflare.0.service=http://${HOSTNAME}:${PORT:-5690}
      - dockflare.0.access.policy=${CFPOLICY:-default_tld}
      - dockflare.0.zonename=${CFDOMAIN}
      - dockflare.0.path=${CFURLPATH:-}
    networks:
        - cloudflare-net
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail -k http://localhost:5690
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
        - TZ=${TZ:-Australia/Melbourne}
        - DISABLE_BUILTIN_AUTH=${DISABLEAUTH:-false}
volumes:
  db:
  steps:

networks:
    cloudflare-net:
        name: cloudflare-net
        external: true
